apiVersion: v2
appVersion: v9.7
description: A Helm chart for XL Release
name: xl-release-oc-helmcharts
version: 1.1.2-alpha

dependencies:

- name: postgresql
  version: 9.8.5
  repository: "https://charts.bitnami.com/bitnami"
  condition: postgresql.install

- name: rabbitmq
  version: 8.6.1
  repository: "https://charts.bitnami.com/bitnami"
  condition: rabbitmq.install


