{{- if or (eq .Values.K8sSetup.Platform "PlainK8s") (eq .Values.K8sSetup.Platform "AWSEKS") (eq .Values.K8sSetup.Platform "AzureAKS") (eq .Values.K8sSetup.Platform "GoogleGKE") }}
{{- if and .Values.ingress.Enabled -}}
{{- $fullName := include "xl-release.fullname" . -}}
{{- $ingressPath := .Values.ingress.path -}}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    app: {{ template "xl-release.name" . }}
    chart: {{ template "xl-release.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- with .Values.ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
{{- if .Values.ingress.tls }}
  tls:
  {{- range .Values.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
  {{- range .Values.ingress.hosts }}
    - host: {{ . }}
      http:
        paths:
          - path: {{ $ingressPath }}
            backend:
              serviceName: {{ $fullName }}
              servicePort: xlr-http
  {{- end }}
{{- end -}}
{{- end -}}
